Feat/merge with master (#3752)
* Fix: [ITEM] Floating label input with icon bug #2835

* FontSize fix for textHeading in scrollable tabs

* checkboxType

* borderColor and fix checkboxType

* TickColor

* use PureComponent for performance

* feat(icomoon): Icomoon icons added

* update fonts fix bug unexpected icon #3213

* feat/Accordian row Disable

* AccordianDisableRow: Disable color

* fix: floatingLabel with defaultValue workiing now

* refactor: Fixed linter warnings

* added useNativeDriver:false to Animated.decay of DeckSwiper

* added useNativeDriver:false to Animated.spring of Fab

* added useNativeDriver to Animated.timing of ToastContainer

* Update index.d.ts

This needs to be fixed to point to right package.json module

* resolving currentlyFocusedField Error

* Add FontAwesome5 style props on type definition

* Update index.js

fix for "TypeError: this.requestAnimationFrame is not a function" bug when using Tabs

* yarn lock updated

* Change react native picker package to correct namespace

* Change imports for react native picker to reference updated package

* minor linting fixes

* v2.15.0

* stale issue close bot

* bot changes

* increased stale period

* date picker value issue fix

* Addresses Expo Web Compatibility
Fixes:
- [X] Use prop-types instead of ViewPropTypes from react-native

* Fixes Icon/selection.json build issue: …
`Module not found: Can't resolve '../basic/Icon/selection.json’`

* ViewPropTypes replaced with PropTypes.shape

* transpiled

* transpiled

* Revert "Feat/accordian disable row"

* reverted files transpiled

* Revert "Revert "Feat/accordian disable row""

* minor linting changes

* v2.15.2

* added title to accordian

* date picker fix

* feat:package.json done

* feat:yarn.lock done

* fix: updated qr added

Co-authored-by: William Paulo <william.paulo@logicasistemas.com.br>
Co-authored-by: Lakshaya Maheshwari <lakshaya.maheshwari@gameskraft.in>
Co-authored-by: Adrien ROCHEDY <arochedy@MacBook-Pro-de-Adrien.local>
Co-authored-by: Abanoub Istfanous <47436634+ElegantSoft@users.noreply.github.com>
Co-authored-by: Hany Kumar <hanykumar@Hanys-MacBook-Air.local>
Co-authored-by: alfianwahid <alfianwahid@hotmail.com>
Co-authored-by: Hany Kumar <hanykumar@Hanys-MacBook-Pro.local>
Co-authored-by: alexandrtovmach <alexandrtovmach@gmail.com>
Co-authored-by: Kelly Copley <copleykj@gmail.com>
Co-authored-by: William Bell <williambell9708@outlook.com>
Co-authored-by: Edin Puzic <edinpuzic11@gmail.com>
Co-authored-by: Darron Park <darron1217@gmail.com>
Co-authored-by: Shivraj <shivraj@geekyants.com>
Co-authored-by: Cyrus Passi <cyruspassi@gmail.com>
Co-authored-by: Lance Castillo <lcastillo88@users.noreply.github.com>
Co-authored-by: Arman Attarzadeh <arman.atz@gmail.com>
Co-authored-by: Ty Rauber <tyrauber@mac.com>
Co-authored-by: Matias <matias.marcelo.calvo@gmail.com>